### PR TITLE
Add ext types2

### PR DESCRIPTION
**Pull request by sschaef**
Supersedes #1

### CODE REVIEW

**Comment by sschaef** [comment]
@xuwei-k I just want to ping you and ask if you are interested in this change?

**Comment by xuwei-k** [comment]
https://github.com/sschaef/msgpack4z-api/commit/10ce6d1889d95a29ed25f3c2391 is unnecessary. `version.sbt` managed by sbt-release plugin

**Comment by sschaef** [comment]
Ok, I removed that commit.

**Comment by xuwei-k** [comment]
Can't serialize extension type data only `packExtensionTypeHeader`( can't use `packBinary` )

**Comment by sschaef** [comment]
On 11/02/2015 10:56 PM, kenji yoshida wrote:
>
> Can't serialize extension type data only |packExtensionTypeHeader|( 
> can't use |packBinary| )
>
I don't understand that comment. Would you please elaborate?

**Comment by vito-c** [comment]
> Can't serialize extension type data only packExtensionTypeHeader( can't use packBinary )
@xuwei-k are you saying that packBinary doesn't work with these changes? do you have a unit test you could add that shows what's breaking?

**Comment by xuwei-k** [comment]
`packBinary` methods for the binary types, not extension type body. see spec and implementations

- https://github.com/msgpack/msgpack/blob/master/spec.md
- https://github.com/msgpack4z/msgpack4z-java07/blob/v0.1.5/src/main/java/msgpack4z/Msgpack07Packer.java#L93-L94
- https://github.com/msgpack4z/msgpack4z-native/blob/v0.1.1/src/main/scala/msgpack4z/MsgOutBuffer.scala#L164
- https://github.com/msgpack4z/msgpack4z-java06/blob/v0.1.1/src/main/java/msgpack4z/Msgpack06Packer.java#L120

**Pull request closed without merging**
